language: android
jdk: oraclejdk7
android:
  components:
    - build-tools-21.1.1
    - android-21
    - sys-img-armeabi-v7a-android-21
    - add-on
    - extra

global:
before_install:
# Commands to excecute before install
- echo "Before install stage"

install:
  - sudo npm install -g cordova



scripts:
    - cd TestCIAndroid
    - cordova build android
