language: android
jdk: oraclejdk7
node_js: "4.1"

android:
  components:
    - build-tools-21.1.1
    - android-21
    - sys-img-armeabi-v7a-android-21
    - add-on
    - extra

global:
before_install:
# Commands to excecute before install
- echo "Before install stage"

install:
#  - curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
#  - sudo apt-get install -y nodejs
  - nvm use v4.1
  - npm install -g cordova



scripts:
    - cd TestCIAndroid
    - cordova build android
