language: android
jdk: oraclejdk7
node_js: "4.1.1"

android:
  components:
    - build-tools-21.1.1
    - android-21
    - sys-img-armeabi-v7a-android-21
    - add-on
    - extra

global:
before_install:
  # Commands to excecute before install
  - echo "Before install stage"
  - nvm install 4.1.1
  - nvm use 4.1.1

install:
  - npm install cordova



scripts:
    - cd TestCIAndroid
    - cordova build android
