language: android
jdk: oraclejdk8
node_js: "4.1.1"

android:
  components:
    - build-tools-22.0.1
    - android-22
    - sys-img-armeabi-v7a-android-22
    - add-on
    - extra

global:
before_install:
  # Commands to excecute before install
  - echo "Before install stage"
  - nvm install 4.1.1
  - nvm use 4.1.1
  - npm install cordova
  - echo "END - Before install stage"

install:
  - echo "Install stage"
  - cd TestCIAndroid
  - cordova prepare
  - cd platforms/android/
  - pwd
  - echo "END - install stage"

#scripts:
#  - echo "Scripts stage"
#  - pwd
#  - ./gradlew build connectedCheck
#  - echo "END Scripts stage"


